name: Build ZopfliPNG for Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSYS2 (MinGW64)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            make

      - name: Build zopflipng.exe (PNG optimizer)
        shell: msys2 {0}
        run: |
          x86_64-w64-mingw32-g++ -O2 -W -Wall -Wextra -static -static-libgcc -static-libstdc++ -Wno-unused-function -ansi -pedantic \
            src/zopfli/blocksplitter.c \
            src/zopfli/cache.c \
            src/zopfli/deflate.c \
            src/zopfli/gzip_container.c \
            src/zopfli/hash.c \
            src/zopfli/katajainen.c \
            src/zopfli/lz77.c \
            src/zopfli/squeeze.c \
            src/zopfli/tree.c \
            src/zopfli/util.c \
            src/zopfli/zlib_container.c \
            src/zopfli/zopfli_lib.c \
            src/zopflipng/zopflipng_bin.cc \
            src/zopflipng/zopflipng_lib.cc \
            src/zopflipng/lodepng/lodepng.cpp \
            src/zopflipng/lodepng/lodepng_util.cpp \
            -I src/ -o zopflipng.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zopfli-windows-binaries
          path: |
            zopflipng.exe
